.TH XWAX "1" "July 2009" "xwax version 0.6" "User Commands"
.SH NAME
xwax \- Open-source vinyl emulation software for Linux
.SH SYNOPSIS
.B xwax
[\fIparameters\fR]
.SH DESCRIPTION
.HP
\fB\-l\fR <directory> Directory to scan for audio tracks
.TP
\fB\-t\fR <name>
Timecode name
.TP
\fB\-i\fR <program>
Specify external importer (default 'xwax_import')
.TP
\fB\-h\fR
Display this message
.SS "OSS device options:"
.TP
\fB\-d\fR <device>
Build a deck connected to OSS audio device
.TP
\fB\-r\fR <hz>
Sample rate (default 44100Hz)
.TP
\fB\-b\fR <n>
Number of buffers (default 8)
.TP
\fB\-f\fR <n>
Buffer size to request (2^n bytes, default 7)
.SS "ALSA device options:"
.TP
\fB\-a\fR <device>
Build a deck connected to ALSA audio device
.TP
\fB\-r\fR <hz>
Sample rate (default 44100Hz)
.TP
\fB\-m\fR <ms>
Buffer time (default 8ms)
.PP
Device options, \fB\-t\fR and \fB\-i\fR apply to subsequent devices.
Decks and audio directories can be specified multiple times.
.SS "Available timecodes (for use with -t):"
.IP
serato_2a (default), serato_2b, serato_cd,
traktor_a, traktor_b, mixvibes_v2
.PP
eg. Standard 2\-deck setup
.IP
xwax \fB\-l\fR ~/music \fB\-d\fR /dev/dsp \fB\-d\fR /dev/dsp1
.PP
eg. Use a larger buffer on a third deck
.IP
xwax \fB\-l\fR ~/music \fB\-d\fR /dev/dsp \fB\-d\fR /dev/dsp1 \fB\-f\fR 10 \fB\-d\fR /dev/dsp2
.PP
eg. Use OSS and ALSA devices simultaneously
.IP
xwax \fB\-l\fR ~/music \fB\-d\fR /dev/dsp \fB\-a\fR hw:1
.SH AUTHOR
xwax was written by Mark Hills <mark@pogo.org.uk>
.PP
This manual page was written by Mitchell Smith <mjs@mjsprojects.net>,
for the Debian project (but may be used by others).
